---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", url: "https://dl-ssl.google.com/linux/linux_signing_key.pub" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        filename: "{{ item.filename }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", filename: "google-chrome", repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", name: "chromium-browser" }
        - { state: "latest", name: "google-chrome-stable" }
