---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        keyserver: "keyserver.ubuntu.com"
        id: "177F4010FE56CA3336300305F1656F24C74CD1D8"

    - name: add-apt-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb [arch=amd64] http://ftp.osuosl.org/pub/mariadb/repo/10.4/ubuntu cosmic main" }

    - name: debconf-set-selections
      debconf:
        name: "{{ item.name }}"
        vtype: "{{ item.vtype }}"
        question: "{{ item.question }}"
        value: "{{ item.value }}"
      with_items:
        - { name: "mariadb-server-10.4", vtype: "password", question: "mysql-server/root_password", value: "" }
        - { name: "mariadb-server-10.4", vtype: "password", question: "mysql-server/root_password_again", value: "" }
      changed_when: false

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "mariadb-client-10.4" }
        - { state: "latest", name: "mariadb-server-10.4" }

    - name: start service
      service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: "mysql", state: "started", enabled: "no" }
      register: start_service_result

    - name: disable mysqsl anonymous access
      shell: |
        mysql -NBe "DELETE FROM mysql.user WHERE User = ''"
      when:
        - start_service_result.results[0].state == "started"
      register: disable_anonymous_access_result
      changed_when: disable_anonymous_access_result is not succeeded
      ignore_errors: yes

    - name: disable mysql root remote access
      shell: |
        mysql -NBe "DELETE FROM mysql.user WHERE User = 'root' AND Host <> 'localhost'"
      when:
        - start_service_result.results[0].state == "started"
      register: disable_root_remote_access_result
      changed_when: disable_root_remote_access_result is not succeeded
      ignore_errors: yes

    - name: enable service
      service:
        name: "{{ item.name }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: "mysql", enabled: "yes" }
