---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", repo: "deb https://deb.nodesource.com/node_11.x cosmic main" }
        - { state: "absent", repo: "deb https://deb.nodesource.com/node_11.x disco main" }
        - { state: "present", repo: "deb https://deb.nodesource.com/node_12.x disco main" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "nodejs" }

    - name: npm install
      npm:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        global: "yes"
        executable: "/usr/bin/npm --unsafe-perm --allow-root"
      with_items:
        - { state: "latest", name: "eslint" }
        - { state: "latest", name: "node-sass" }
        - { state: "latest", name: "sass-lint" }
