---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", url: "https://download.opensuse.org/repositories/home:cabelo/xUbuntu_19.04/Release.key" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb http://download.opensuse.org/repositories/home:/cabelo/xUbuntu_19.04/ /" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "owasp-zap" }

    - name: copy templates
      template:
        src: "./templates{{ item.dest }}.j2"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0644') }}"
      with_items:
        - { dest: "/usr/share/applications/owasp-zap.desktop" }
