---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", repo: "ppa:ondrej/php" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        install_recommends: "no"
      with_items:
        - { state: "latest", name: "geoip-database" }
        - { state: "latest", name: "imagemagick" }
        - { state: "latest", name: "libssl-dev" }
        - { state: "latest", name: "mariadb-client" }
        - { state: "latest", name: "postgresql-client" }
        - { state: "latest", name: "sqlite3" }
        - { state: "latest", name: "php7.3-bcmath" }
        - { state: "latest", name: "php7.3-bz2" }
        - { state: "latest", name: "php7.3-cli" }
        - { state: "latest", name: "php7.3-curl" }
        - { state: "latest", name: "php7.3-fpm" }
        - { state: "latest", name: "php7.3-gd" }
        - { state: "latest", name: "php7.3-imap" }
        - { state: "latest", name: "php7.3-intl" }
        - { state: "latest", name: "php7.3-json" }
        - { state: "latest", name: "php7.3-ldap" }
        - { state: "latest", name: "php7.3-mbstring" }
        - { state: "latest", name: "php7.3-mysql" }
        - { state: "latest", name: "php7.3-opcache" }
        - { state: "latest", name: "php7.3-pgsql" }
        - { state: "latest", name: "php7.3-soap" }
        - { state: "latest", name: "php7.3-sqlite3" }
        - { state: "latest", name: "php7.3-tidy" }
        - { state: "latest", name: "php7.3-xml" }
        - { state: "latest", name: "php7.3-xmlrpc" }
        - { state: "latest", name: "php7.3-xsl" }
        - { state: "latest", name: "php7.3-zip" }
        - { state: "latest", name: "php-apcu" }
        - { state: "latest", name: "php-apcu-bc" }
        - { state: "latest", name: "php-geoip" }
        - { state: "latest", name: "php-imagick" }
        - { state: "latest", name: "php-memcached" }
        - { state: "latest", name: "php-uuid" }
        - { state: "latest", name: "php-xdebug" }

    - name: phpenmod
      php_module:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", name: "apcu" }
        - { state: "present", name: "apcu_bc" }
        - { state: "present", name: "bcmath" }
        - { state: "present", name: "bz2" }
        - { state: "present", name: "calendar" }
        - { state: "present", name: "ctype" }
        - { state: "present", name: "curl" }
        - { state: "present", name: "dom" }
        - { state: "present", name: "exif" }
        - { state: "present", name: "fileinfo" }
        - { state: "present", name: "ftp" }
        - { state: "present", name: "gd" }
        - { state: "present", name: "gettext" }
        - { state: "present", name: "iconv" }
        - { state: "present", name: "imap" }
        - { state: "present", name: "intl" }
        - { state: "present", name: "json" }
        - { state: "present", name: "ldap" }
        - { state: "present", name: "mbstring" }
        - { state: "present", name: "memcache" }
        - { state: "present", name: "mysqli" }
        - { state: "present", name: "mysqlnd" }
        - { state: "present", name: "opcache" }
        - { state: "present", name: "pdo" }
        - { state: "present", name: "pdo_mysql" }
        - { state: "present", name: "pdo_pgsql" }
        - { state: "present", name: "pdo_sqlite" }
        - { state: "present", name: "phar" }
        - { state: "present", name: "posix" }
        - { state: "present", name: "readline" }
        - { state: "present", name: "shmop" }
        - { state: "present", name: "simplexml" }
        - { state: "present", name: "snmp" }
        - { state: "present", name: "soap" }
        - { state: "present", name: "sockets" }
        - { state: "present", name: "sysvmsg" }
        - { state: "present", name: "sysvsem" }
        - { state: "present", name: "sysvshm" }
        - { state: "present", name: "tidy" }
        - { state: "present", name: "tokenizer" }
        - { state: "present", name: "uuid" }
        - { state: "present", name: "wddx" }
        - { state: "present", name: "xml" }
        - { state: "present", name: "xmlreader" }
        - { state: "present", name: "xmlrpc" }
        - { state: "present", name: "xmlwriter" }
        - { state: "present", name: "xsl" }
        - { state: "present", name: "zip" }

    - name: enable service
      service:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: "php7.3-fpm", state: "started", enabled: "no" }

    - name: install composer globally
      shell: |
        curl -sL https://getcomposer.org/download/1.7.3/composer.phar > /usr/local/bin/composer
        chown root:root /usr/local/bin/composer
        chmod 777 /usr/local/bin/composer
      args:
        creates: "/usr/local/bin/composer"

    - name: composer self-update
      shell: |
        composer self-update --no-interaction
      register: composer_self_update_result
      changed_when: "'You are already using composer' not in composer_self_update_result.stderr"
      ignore_errors: yes

    - name: composer global init
      shell: |
        mkdir -p $COMPOSER_HOME
        composer global init --no-interaction
      register: composer_global_init_result
      changed_when: composer_global_init_result is not succeeded
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"

    - name: composer global require
      shell: |
        composer global {{ item.status }} {{ item.name }} --no-interaction
      with_items:
        - { status: 'require', name: 'hirak/prestissimo:@stable' }
        - { status: 'require', name: 'consolidation/cgr:@stable' }
      register: composer_global_require_result
      changed_when: composer_global_require_result is not succeeded
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"

    - name: cgr require
      shell: |
        cgr require {{ item.name }}
      with_items:
        - { name: "drupal/coder:@stable" }
        - { name: "drush/drush-launcher:@stable" }
        - { name: "friendsofphp/php-cs-fixer:@stable" }
        - { name: "phpunit/phpunit:@stable" }
        - { name: "sami/sami:@stable" }
        - { name: "squizlabs/php_codesniffer:@stable" }
      register: cgr_require_result
      changed_when: cgr_require_result is not succeeded
      ignore_errors: "yes"
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"
        CGR_BIN_DIR: "/usr/local/bin"

    - name: cgr update
      shell: |
        cgr update
      register: cgr_update_result
      changed_when: "'Package operations:' in cgr_update_result.stderr"
      ignore_errors: "yes"
      environment:
        COMPOSER_HOME: "/usr/local/share/composer"
        COMPOSER_BIN_DIR: "/usr/local/bin"
        CGR_BIN_DIR: "/usr/local/bin"
