---

- hosts: all
  remote_user: root
  tasks:
    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "hibernate" }
        - { state: "latest", name: "pm-utils" }

    - name: Enable hibernate by default in upower
      replace:
        path: /var/lib/polkit-1/localauthority/10-vendor.d/com.ubuntu.desktop.pkla
        regexp: '^(\[Disable hibernate by default in upower\][^\[]*)ResultActive=no'
        replace: '\1ResultActive=yes'
    
    - name: Enable hibernate by default in logind
      replace:
        path: /var/lib/polkit-1/localauthority/10-vendor.d/com.ubuntu.desktop.pkla
        regexp: '^(\[Disable hibernate by default in logind\][^\[]*)ResultActive=no'
        replace: '\1ResultActive=yes'

    - name: HandleLidSwitch=hibernate
      replace:
        path: /etc/systemd/logind.conf
        regexp: '^#*HandleLidSwitch=.*'
        replace: 'HandleLidSwitch=hibernate'
      register: replace_result
