---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-get dist-upgrade
      apt:
        cache_valid_time: "3600"
        update_cache: "yes"
        upgrade: "dist"

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "apt-transport-https" }
        - { state: "latest", name: "aptitude" }
        - { state: "latest", name: "ca-certificates" }
        - { state: "latest", name: "debian-keyring" }
        - { state: "latest", name: "debian-archive-keyring" }
        - { state: "latest", name: "dselect" }
        - { state: "latest", name: "linux-generic" }
        - { state: "latest", name: "python" }
        - { state: "latest", name: "python-pip" }
        - { state: "latest", name: "tasksel" }

    - name: dselect update
      shell: |
        dselect update
      register: dselect_update_result
      changed_when: dselect_update_result.rc != 0

    - name: tasksel install
      shell: |
        tasksel install {{ item.name }}
      with_items:
        - { name: "openssh-server" }
        - { name: "server" }
        - { name: "ubuntu-gnome-desktop" }
        - { name: "ubuntustudio-fonts" }
        - { name: "ubuntustudio-graphics" }
        - { name: "ubuntustudio-photography" }
        - { name: "ubuntustudio-publishing" }
        - { name: "ubuntustudio-video" }
      register: tasksel_update_result
      changed_when: tasksel_update_result.rc != 0

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "ppa:graphics-drivers/ppa" }

    - name: ubuntu-drivers autoinstall
      shell: |
        ubuntu-drivers autoinstall
      register: ubuntu_drivers_autoinstall_result
      changed_when: ubuntu_drivers_autoinstall_result.rc != 0
