---

- hosts: all
  remote_user: root
  tasks:
    - name: copy templates
      template:
        src: "./templates{{ item.dest }}.j2"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0644') }}"
      with_items:
        - { dest: "/etc/apt/sources.list" }
        - { dest: "/etc/dconf/db/ibus.d/99-custom-settings" }
        - { dest: "/etc/ssh/ssh_config" }

    - name: apt-get dist-upgrade
      apt:
        cache_valid_time: "3600"
        update_cache: "yes"
        upgrade: "dist"

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", name: "cloud-init" }
        - { state: "latest", name: "apt-transport-https" }
        - { state: "latest", name: "aptitude" }
        - { state: "latest", name: "build-essential" }
        - { state: "latest", name: "ca-certificates" }
        - { state: "latest", name: "debian-archive-keyring" }
        - { state: "latest", name: "debian-keyring" }
        - { state: "latest", name: "dselect" }
        - { state: "latest", name: "linux-generic" }
        - { state: "latest", name: "openssh-server" }
        - { state: "latest", name: "python3" }
        - { state: "latest", name: "python3-dev" }
        - { state: "latest", name: "tasksel" }
        - { state: "latest", name: "ubuntu-desktop" }
        - { state: "latest", name: "ubuntu-server" }
#        - { state: "latest", name: "vanilla-gnome-desktop" }

#    - name: apt-add-repository
#      apt_repository:
#        repo: "{{ item.repo }}"
#        state: "{{ item.state }}"
#      with_items:
#        - { state: "present", repo: "ppa:graphics-drivers/ppa" }
#        - { state: "absent", repo: "ppa:ubuntu-x-swat/updates" }

    - name: ubuntu-drivers autoinstall
      shell: |
        ubuntu-drivers autoinstall
      changed_when: false
      ignore_errors: true

    - name: fwupdmgr -y update
      shell: |
        fwupdmgr -y update
      changed_when: false
      ignore_errors: true

    - name: dconf update
      shell: |
        dconf update
      changed_when: false
      ignore_errors: true

    - name: enforce gdm3 with xorg
      lineinfile:
        path: "/etc/gdm3/custom.conf"
        regexp: "^.*WaylandEnable=false$"
        line: "WaylandEnable=false"
        state: "present"

    - name: fix grub2
      shell: |
        cp /usr/share/grub/*.pf2 /boot/grub/
        sed -i 's/^\(GRUB_HIDDEN_TIMEOUT\)=\(.*\)$/#\1=\2/g' /etc/default/grub
        sed -i 's/^\(GRUB_HIDDEN_TIMEOUT_QUIET\)=\(.*\)$/#\1=\2/g' /etc/default/grub
        sed -i 's/^\(GRUB_TIMEOUT\)=\(.*\)$/\1=3/g' /etc/default/grub
        sed -i 's/^\(GRUB_CMDLINE_LINUX\)=\(.*\)$/\1="cgroup_enable=memory swapaccount=1"/g' /etc/default/grub
        update-grub
      register: fix_grub2_result
      changed_when: fix_grub2_result is not succeeded

    - name: fix resolv.conf
      file:
        src: "/run/systemd/resolve/resolv.conf"
        dest: "/etc/resolv.conf"
        state: "link"
        force: "yes"

    - name: fix RTC in UTC
      shell: |
        timedatectl set-local-rtc 0 --adjust-system-clock
      changed_when: false
      ignore_errors: true

    - name: disable network printer auto detect
      shell: |
        sed -i 's/^#*\s*BrowseRemoteProtocols.*$/BrowseRemoteProtocols none/g' /etc/cups/cups-browsed.conf
        sed -i 's/^#*\s*BrowseLocalProtocols.*$/BrowseLocalProtocols none/g' /etc/cups/cups-browsed.conf
        sed -i 's/^#*\s*BrowseProtocols.*$/BrowseProtocols none/g' /etc/cups/cups-browsed.conf
        systemctl restart cups-browsed
        systemctl restart cups
      changed_when: false
      ignore_errors: true
