---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", url: "https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb http://linux.teamviewer.com/deb stable main" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "teamviewer" }

    - name: remove duplicated apt source list
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", path: "/etc/apt/sources.list.d/teamviewer.list" }
        - { state: "absent", path: "/etc/apt/sources.list.d/teamviewer.list.save" }
