---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian eoan contrib" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", name: "virtualbox-6.0" }
        - { state: "latest", name: "dkms" }
        - { state: "latest", name: "virtualbox-6.1" }
